name: Auto Release

on:
  schedule:
    - cron: '0 3 */5 * *'    # 每5天UTC 3点运行
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Generate version
        id: set_version
        run: |
          DATE=$(date +'%Y%m%d')
          COUNT=$(git tag | grep "v$DATE" | wc -l)
          VERSION="v$DATE.$((COUNT+1))"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set Run Time
        id: set_time
        run: echo "run_time=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Zip project
        run: |
          zip -r "AD广告收集.zip" . -x "*.git*" ".github/*"  # 可排除.git和github workflows自身

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_version.outputs.version }}
          name: "AD广告收集 ${{ steps.set_version.outputs.version }}"
          body: |
            本次为自动打包发布，包含项目全部内容。
            触发时间：${{ steps.set_time.outputs.run_time }}
          files: AD广告收集.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
