name: Sync Issues to AdSuper

permissions:
  contents: write
  issues: read
  pull-requests: read
  projects: read

on:
  schedule:
    - cron: '0 2 */5 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install PyGithub requests

      - name: Run sync script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python sync_issues.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add AdSuper.txt adnew.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update rules from issues [skip ci]"
          git push
